version: "3.7"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./client/app/wallet/db:/app/wallet/db # this is to store the wallet db persistently
    environment:
      - WALLET_DB=/app/wallet/db/db
      - FUND_MANAGER_HOST=server
      - FUND_MANAGER_API_PORT=80
      - ETH_HOST=https://eth.ap.idc.ac.il
